// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_create from "./routes/api/create.ts";
import * as $api_end from "./routes/api/end.ts";
import * as $api_game_gameId_distribution_change_roleName_ from "./routes/api/game/[gameId]/distribution/change/[roleName].ts";
import * as $api_player_gameId_playerId_ from "./routes/api/player/[gameId]/[playerId].ts";
import * as $api_register from "./routes/api/register.ts";
import * as $api_start from "./routes/api/start.ts";
import * as $index from "./routes/index.tsx";
import * as $play_gameId_ from "./routes/play/[gameId].tsx";
import * as $play_gameId_playerId_ from "./routes/play/[gameId]/[playerId].tsx";
import * as $play_index from "./routes/play/index.tsx";
import * as $sse_change from "./routes/sse/change.ts";
import * as $sse_game_gameId_ from "./routes/sse/game/[gameId].ts";
import * as $sse_player_playerId_ from "./routes/sse/player/[playerId].ts";
import * as $Card from "./islands/Card.tsx";
import * as $GameOverview from "./islands/GameOverview.tsx";
import * as $QrDialog from "./islands/QrDialog.tsx";
import * as $StartButton from "./islands/StartButton.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/create.ts": $api_create,
    "./routes/api/end.ts": $api_end,
    "./routes/api/game/[gameId]/distribution/change/[roleName].ts":
      $api_game_gameId_distribution_change_roleName_,
    "./routes/api/player/[gameId]/[playerId].ts": $api_player_gameId_playerId_,
    "./routes/api/register.ts": $api_register,
    "./routes/api/start.ts": $api_start,
    "./routes/index.tsx": $index,
    "./routes/play/[gameId].tsx": $play_gameId_,
    "./routes/play/[gameId]/[playerId].tsx": $play_gameId_playerId_,
    "./routes/play/index.tsx": $play_index,
    "./routes/sse/change.ts": $sse_change,
    "./routes/sse/game/[gameId].ts": $sse_game_gameId_,
    "./routes/sse/player/[playerId].ts": $sse_player_playerId_,
  },
  islands: {
    "./islands/Card.tsx": $Card,
    "./islands/GameOverview.tsx": $GameOverview,
    "./islands/QrDialog.tsx": $QrDialog,
    "./islands/StartButton.tsx": $StartButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
